export const roleThemes = {
  student: {
    portalTitle: "CampusConnect",
    portalSubtitle: "Student Portal",
    tagline: "Stay updated. Get involved. Succeed together.",
    heading: "Welcome Back!",
    subheading: "Login to access your student dashboard",
    idLabel: "Registration Number",
    idPlaceholder: "Enter registration number",
    footerText: "New here?",
    footerLinkText: "Register as Student",
    actions: [
      { label: "View Events", icon: "Calendar" },
      { label: "Mark Attendance", icon: "ClipboardCheck" },
      { label: "Check Reports", icon: "BarChart3" },
      { label: "Update Profile", icon: "UserCircle" },
    ],
  },
  admin: {
    portalTitle: "Campus Management System",
    portalSubtitle: "Admin Portal",
    tagline: "Manage. Monitor. Make an impact.",
    heading: "Welcome Admin!",
    subheading: "Login to access the admin dashboard",
    idLabel: "Admin ID / Email",
    idPlaceholder: "Enter admin ID or email",
    footerText: "Need help?",
    footerLinkText: "Contact System Admin",
    actions: [
      { label: "Manage Events", icon: "Calendar" },
      { label: "Manage Attendance", icon: "Users" },
      { label: "Generate Reports", icon: "PieChart" },
      { label: "Manage Users", icon: "UserCog" },
    ],
  },
};